print("****** MENU MATEMÁTICO ******")  
print("Se voçé quiser sair, digite SAIR.")
print("Digite um número para escolher a operação desejada:")
print("1 = Adição")
print("1 - Adição")
print("2 - Subtração")
print("3 - Multiplicação")
print("4 - Divisão")
print("5 - Par ou Ímpar")
print("6 - Número Primo")
print("7 - Fatorial")
print("Digite 'Sair' para finalizar.")
print("*****************************")
